version: '3.8'

services:
  graphgen:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphgen:offline-latest
    container_name: graphgen-app
    ports:
      - "7860:7860"
    environment:
      # 模型配置
      - SYNTHESIZER_MODEL=${SYNTHESIZER_MODEL:-Qwen/Qwen2.5-7B-Instruct}
      - SYNTHESIZER_BASE_URL=${SYNTHESIZER_BASE_URL:-https://api.siliconflow.cn/v1}
      - SYNTHESIZER_API_KEY=${SYNTHESIZER_API_KEY:-}
      - TRAINEE_MODEL=${TRAINEE_MODEL:-Qwen/Qwen2.5-7B-Instruct}
      - TRAINEE_BASE_URL=${TRAINEE_BASE_URL:-https://api.siliconflow.cn/v1}
      - TRAINEE_API_KEY=${TRAINEE_API_KEY:-}
      
      # 速率限制
      - RPM=${RPM:-1000}
      - TPM=${TPM:-50000}
      
      # 离线模式设置
      - GRAPHGEN_OFFLINE_MODE=true
      - HF_DATASETS_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      
      # 缓存路径
      - HF_HOME=/app/cache/huggingface
      - TRANSFORMERS_CACHE=/app/cache/huggingface/transformers
      - HF_DATASETS_CACHE=/app/cache/huggingface/datasets
      - TIKTOKEN_CACHE_DIR=/app/cache/tiktoken
      - NLTK_DATA=/app/resources/nltk_data
      
    volumes:
      # 持久化缓存和日志
      - graphgen_cache:/app/cache
      - graphgen_logs:/app/logs
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    # 资源限制（可选）
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  graphgen_cache:
    driver: local
  graphgen_logs:
    driver: local