# GraphGen 多跳推理问答对生成配置文件
# 此配置用于生成需要跨多个实体进行推理的复杂问答对
# 适用于训练模型的多步推理和逻辑推理能力

# === 输入配置 ===
input_data_type: raw  # 输入数据类型: raw(原始文档) 或 chunked(预分块数据)
input_file: resources/input_examples/技术通讯_交易中心数字证书的前世今生_trunk.txt  # 输入文件路径，支持json、jsonl、txt格式，参考resources/input_examples中的示例

# === 输出配置 ===
output_data_type: multi_hop  # 输出数据类型: atomic(原子性), aggregated(聚合型), multi_hop(多跳推理), cot(思维链)
output_data_format: ChatML   # 输出格式: Alpaca(指令微调格式), ShareGPT(对话格式), ChatML(聊天标记语言)

# === 分词器配置 ===
tokenizer: cl100k_base  # 用于Token计数的分词器，支持tiktoken分词器名称和本地分词器路径

# === 外部搜索配置 ===
search:
  enabled: false  # 是否启用外部搜索来补充知识图谱信息
  search_types: ["google"]  # 搜索引擎类型，支持: google, bing, uniprot, wikipedia

# === 知识缺口识别策略 ===
# 通过Quiz测试和判断来识别LLM对知识点的掌握程度
quiz_and_judge_strategy:
  enabled: true        # 是否启用Quiz和判断策略
  quiz_samples: 2      # 生成的Quiz样本数量
  re_judge: false      # 是否重新判断已有的Quiz样本

# === 图遍历策略 ===
# 使用理解损失对子图进行聚类的策略配置
traverse_strategy:
  bidirectional: true           # 是否双向遍历图（正向和反向）
  edge_sampling: max_loss       # 边采样策略: random(随机), max_loss(最大损失优先), min_loss(最小损失优先)
  expand_method: max_width      # 扩展方法: max_width(宽度优先), max_depth(深度优先)
  isolated_node_strategy: ignore  # 孤立节点处理策略: ignore(忽略), add(添加)
  max_depth: 3                  # 图遍历的最大深度（多跳推理需要更深的遍历）
  max_extra_edges: 10           # 每个方向的最大边数（多跳推理需要更多边连接）
  max_tokens: 256              # 限制输入长度（当expand_method="max_tokens"时）
  loss_strategy: only_edge     # 损失计算重点: only_edge(仅边), both(边和节点)
